version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'
    restart: always
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - mongodb

volumes:
  mongodata:
