version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
    networks:
      - fastapi-network

volumes:
  mongodata:

networks:
  fastapi-network:
    driver: bridge